name: pr_ci_frontend
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  frontend:
    name: Run PR Frontend Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node environment
        uses: actions/setup-node@v3

      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: "frontend"

      - name: Install Prettier
        run: yarn add prettier

      - name: Run Prettier - Formatting check
        working-directory: ./frontend
        run: |
          yarn prettier . --check --config ../.prettierrc --ignore-path ../.prettierignore
        continue-on-error: true

      - name: Run Type Check
        uses: borales/actions-yarn@v4
        with:
          cmd: nuxi typecheck
          dir: "frontend"
        continue-on-error: true

      - name: Run eslint - Linting
        uses: borales/actions-yarn@v4
        with:
          cmd: eslint . --ext .js,.vue
          dir: "frontend"

      # - name: Run Axe - Accessibility check
      #   working-directory: ./frontend
      #   run: |
      #     yarn add -D axe-core vue-axe@next
      #   continue-on-error: true

      - name: Run Axe - Accessibility check
        working-directory: ./frontend
        run: |
          yarn global add @axe-core/cli
          axe http://localhost:3000 --exit
        continue-on-error: true

